services:
  myappangular:
    image: myappangular
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7001:7001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
